---
- hosts: all
  remote_user: pi
  sudo: yes
  tasks:
    - name: install python-pip
      package: name=python-pip state=latest
    - name: install python-dev
      package: name=python-dev state=latest
    - name: install build-essential
      package: name=build-essential state=latest
    - name: install bluez
      package: name=bluez update_cache=yes state=latest
    - name: install python-bluez
      package: name=python-bluez update_cache=yes state=latest
    - name: install pi-bluetooth
      package: name=pi-bluetooth update_cache=yes state=latest
    - name: install obexpushd
      package: name=obexpushd update_cache=yes state=latest
    - name: install raspberrypi-sys-mods
      package: name=raspberrypi-sys-mods update_cache=yes state=latest
