---
- hosts: all
  remote_user: pi
  become: yes
  tasks:
  - name: pull changes
    shell: chdir=/home/pi/repo/sensor git pull

  - name: install nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: install pip
    yum: name=python-pip state=present

  - name: install flask
    pip: name=flask

  - name: install smbus
    pip: name=smbus

  - name: add line to fstab
    lineinfile:
      path: /etc/fstab
      line: 'tmpfs  /var/log/nginx/    tmpfs    defaults,noatime,nosuid,mode=0755,size=100m    0 0 \n'

  - name: cron - run start.sh to start flask and nginx
    cron:
      user: pi
      name: "run start.sh to start flask and nginx"
      special_time: reboot
      job: "/home/pi/repo/sensor/start.sh"

  - name: cron - run sensor
    cron:
      user: pi
      name: "run ambiant sensor and write to ramdisk"
      minute: "*/15"
      job: "/usr/bin/python /home/pi/repo/sensor/sensor-ambiant.py"
