---
- hosts: all
  remote_user: pi
  become: yes
  tasks:
  - name: pull changes
    shell: chdir=/home/pi/repo/ git pull

  - name: set permissions
    file:
      path: /home/pi/repo/
      state: directory
      owner: pi
      group: pi
      mode: u=rwX,g=rX,o=rX
      recurse: yes
    become: yes

  - name: install pip
    yum: name=python-pip state=present

  - name: install flask
    pip: name=flask

  - name: install gTTS
    pip: name=gTTS

  - name: Apt install 
    apt: 
      name: ['nginx', 'fortune', 'espeak', 'lynx', 'mplayer', 'omxplayer']
      state: latest
      update_cache: yes
    tags:
    - this

  - name: Add mount nginx to fstab
    lineinfile:
      path: /etc/fstab
      line: 'tmpfs  /var/log/nginx/    tmpfs    defaults,noatime,nosuid,mode=0755,size=100m    0 0'

  - name: Add usb/media to fstab
    lineinfile:
      path: /etc/fstab
      line: 'UUID=18A9-9943 /media vfat auto,nofail,noatime,users,rw,uid=pi,gid=pi 0 0'

  - name: cron - run start.sh to start flask and nginx
    cron:
      user: pi
      name: "run start.sh to start speakerapp"
      special_time: reboot
      job: "/home/pi/repo/speaker/start.sh"

