---
- hosts: all
  remote_user: pi
  become: yes
  tasks:
  - name: pull changes
    shell: chdir=/home/pi/repo/ git pull

  - name: set permissions
    file:
      path: /home/pi/repo/
      state: directory
      owner: pi
      group: pi
      mode: u=rwX,g=rX,o=rX
      recurse: yes
    become: yes

  - name: install nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: install pip
    yum: name=python-pip state=present

  - name: install flask
    pip: name=flask

  - name: install mplayer
    apt: 
      name: mplayer
      state: latest
      update_cache: yes

  - name: add line to fstab
    lineinfile:
      path: /etc/fstab
      line: 'tmpfs  /var/log/nginx/    tmpfs    defaults,noatime,nosuid,mode=0755,size=100m    0 0 \n'
