---
- hosts: alarm
  remote_user: pi
  sudo: yes
  tasks:
    - name: test connection
      ping:
      tags:
        - ping
    - name: make directories
      file: path=/var/www/{{item}} state=directory
      with_items:
        - mp3
        - mp3/wakeup
        - mp3/sleep
        - app
      tags: 
        - mkdirs
    - name: copy mp3
      sudo: yes
      synchronize: src=~/Music/pi-alarm-mp3/mp3 dest=/var/www/
      tags:
        - copymp3s
    - name: copy scripts
      sudo: yes
      copy: 
        src="{{ item }}" 
        dest=/var/www/
        owner=root 
        group=root 
        mode=0777 
        force=true
      with_fileglob:
        - ~/Repos/raspberry-pi/clock3/*.sh
        - ~/Repos/raspberry-pi/clock3/*.py
      tags: 
        - copyscripts
    - name: copyIndex
      copy: src=~/Repos/raspberry-pi/clock3/index.php
        dest=/var/www/html/
        owner=root 
        group=root 
        mode=0777 
        force=true
      tags: 
        - copyIndex 
    - name: copy flask files
      sudo: yes
      copy: src=~/Repos/raspberry-pi/clock3/app
        dest=/var/www
        owner=root 
        group=root 
        mode=0777 
        force=true
      tags:
        - flask
    - name: copy monit files
      sudo: yes
      copy: src=~/Repos/raspberry-pi/clock3/conf.d/
        dest=/etc/monit/conf.d/
        owner=root 
        group=root 
        mode=0777 
        force=true
      tags:
        - flask
        - monit
    - name: install apache2
      package: name=apache2 state=latest
    - name: install python-pip
      package: name=python-pip state=latest
    - name: install python-dev
      package: name=python-dev state=latest
    - name: install build-essential
      package: name=build-essential state=latest
    - name: install omxplayer
      package: name=omxplayer state=latest
    - name: install monit
      package: name=monit state=latest
    - name: install pytz
      pip: name=pytz 
    - name: install flask
      pip: name=flask 
      tags:
        - flask
    - name: install python-crontab
      pip: name=python-crontab
    - name: install jinja2
      pip: name=jinja2
    - name: install ntpd
      package: name=ntpdate state=latest
    - name: restart apache2
      service: name=apache2 state=restarted
      tags: restartApache
    - name: stop flask
      shell: /var/www/stopApp.sh
      tags: 
      - stopApp
      - restartApp
    - name: start flask
      shell: /var/www/startApp.sh
      tags: 
        - startApp
        - restartApp
        
