---
- hosts: picron
  remote_user: pi
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: install python-pip
      package: name=python-pip state=latest
    - name: install python-dev
      package: name=python-dev state=latest
    - name: install build-essential
      package: name=build-essential state=latest
    - name: install omxplayer
      package: name=omxplayer state=latest
    - name: install monit
      apt: name=monit state=latest
    - name: configure http port in monitrc
      lineinfile: dest=/etc/monit/monitrc
            regexp='# set httpd port 2812 and'
            insertbefore='# set httpd port 2812 and'
            line="set httpd port 2812 and\n  use address localhost\n  allow localhost"
    - name: install pytz
      pip: name=pytz 
    - name: install flask
      pip: name=flask 
    - name: install python-crontab
      pip: name=python-crontab
    - name: install jinja2
      pip: name=jinja2
    - name: install ntpd
      package: name=ntpdate state=latest
    - name: Copy timezone file
      sudo: yes
      copy: src=~/Repos/raspberry-pi/picron/etc/timezone
        dest=/etc/
        owner=root
        group=root
        mode=0755
        force=true
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: install mpd
      apt: name=mpd update_cache=yes state=latest
    - name: install mpc
      apt: name=mpc update_cache=yes state=latest
