---
- hosts: pigate
  remote_user: pi
  become_method: sudo
  sudo: yes
  tasks:
    - name: test connection
      ping:
      tags:
        - ping
    - name: install monit
      package: name=monit state=latest
    - name: install pytz
      pip: name=pytz 
